name = "rw-sync"
main = "src/index.ts"
compatibility_date = "2022-06-23"

[triggers]
crons = ["*/5 * * * *"] # every 5 minutes

[vars]
CUSTOM_HEADER_LINK = "[RedwoodJS's Notion](https://www.notion.so/redwoodjs/Next-release-3-3-0-f12dfa06faf24334bad04dd4b3104f4f)"
ENABLE_FETCH = "1"
