name = "guild-sync"
main = "src/index.ts"
compatibility_date = "2022-06-23"

[triggers]
crons = ["*/5 * * * *"] # every 5 minutes

[vars]
CUSTOM_HEADER_LINK = "[The Guild's](https://the-guild.dev)"
ENABLE_FETCH = "1"
IGNORED_REPOS = "the-guild-org/crisp-chats"